spring.application.name=ExquisiteLoop
server.port=8080

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

email.from.default=hello@exquisiteloop.com
email.to.default=hello@exquisiteloop.com
email.error=hello@exquisiteloop.com

spring.mail.host=${EXQLOOP_SMTP_HOST}
spring.mail.port=${EXQLOOP_SMTP_PORT}
spring.mail.protocol=smtps
spring.mail.username=${EXQLOOP_SMTP_USER}
spring.mail.password=${EXQLOOP_SMTP_PASS}

google.analytics.id=${EXQLOOP_ANALYTICS_ID:}

google.recaptcha.key.site=${EXQLOOP_RECAPTCHA_SITEKEY}
google.recaptcha.key.secret=${EXQLOOP_RECAPTCHA_SECRETKEY}